### ISSUE TITLE
Widcard Character

### ISSUE THREAD

**Issue by max-kov** [harleygn/WordsWithChilwell#1]

**Comment by harleygn** [comment]
Implemented, but currently encountering the following errors:
- When selecting 'replace the tiles you used', sometimes an extra tile is added
- At some point, the game will crash with an error in the UpdateScoreWithPenalty function

**Comment by harleygn** [comment]
Solved the penalty issue. Error arose when the game attempted to calculate the player's final score at the end of the game, by subtracting the values of all the characters left in the player's hand. As the wildcard had no specified value, it crashed. Solved by adding all the tiles to a 'library', and setting wildcard to have value of 0.

**Comment by harleygn** [comment]
#
